# Habilita a API genérica de Sensores do Zephyr.
# O sistema de build verá o `compatible` no overlay e habilitará
# automaticamente CONFIG_FXOS8700 e CONFIG_I2C como dependências.
CONFIG_SENSOR=y
CONFIG_GPIO=y

# Habilita a função printk()
CONFIG_SERIAL=y
# Habilita o suporte a números de ponto flutuante na função printk
CONFIG_NEWLIB_LIBC=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Adicionais
CONFIG_PRINTK=y
CONFIG_ADC=y
CONFIG_I2C=y
CONFIG_FXOS8700=y
CONFIG_FXOS8700_MODE_ACCEL=y
CONFIG_MAIN_STACK_SIZE=2048
